//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class clp_sv_answer_choice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clp_sv_answer_choice()
        {
            this.clp_sv_question_response = new HashSet<clp_sv_question_response>();
        }
    
        public int pk1 { get; set; }
        public int clp_sv_subquestion_pk1 { get; set; }
        public int display_order { get; set; }
        public string name { get; set; }
        public Nullable<int> points { get; set; }
        public string open_ended_ind { get; set; }
        public string open_ended_text { get; set; }
        public string not_applicable_ind { get; set; }
    
        public virtual clp_sv_subquestion clp_sv_subquestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clp_sv_question_response> clp_sv_question_response { get; set; }
    }
}
