//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class clp_sv_visual_element
    {
        public int pk1 { get; set; }
        public int clp_sv_survey_pk1 { get; set; }
        public int display_order { get; set; }
        public string style { get; set; }
        public string visual_elem_type { get; set; }
        public string content_body { get; set; }
        public string content_type { get; set; }
        public string new_page_ind { get; set; }
    
        public virtual clp_sv_survey clp_sv_survey { get; set; }
    }
}
