//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class clp_sv_survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clp_sv_survey()
        {
            this.clp_sv_question = new HashSet<clp_sv_question>();
            this.clp_sv_survey_deployment = new HashSet<clp_sv_survey_deployment>();
            this.clp_sv_survey_user = new HashSet<clp_sv_survey_user>();
            this.clp_sv_visual_element = new HashSet<clp_sv_visual_element>();
        }
    
        public int pk1 { get; set; }
        public string name { get; set; }
        public string instrument_key { get; set; }
        public string description { get; set; }
        public Nullable<int> head_survey_pk1 { get; set; }
        public Nullable<int> work_ctx_pk1 { get; set; }
        public string header_body { get; set; }
        public string header_type { get; set; }
        public string footer_body { get; set; }
        public string footer_type { get; set; }
        public string allow_backtracking { get; set; }
        public System.DateTime dtcreated { get; set; }
        public Nullable<decimal> dtmodified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clp_sv_question> clp_sv_question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clp_sv_survey_deployment> clp_sv_survey_deployment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clp_sv_survey_user> clp_sv_survey_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clp_sv_visual_element> clp_sv_visual_element { get; set; }
    }
}
