//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class clp_sv_question_response
    {
        public int pk1 { get; set; }
        public int clp_sv_answer_choice_pk1 { get; set; }
        public int deployment_response_pk1 { get; set; }
        public string answer_text { get; set; }
    
        public virtual clp_sv_answer_choice clp_sv_answer_choice { get; set; }
        public virtual deployment_response deployment_response { get; set; }
    }
}
