//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment_recipient
    {
        public int pk1 { get; set; }
        public int materialized_list_pk1 { get; set; }
        public Nullable<int> user_pk1 { get; set; }
        public Nullable<int> course_pk1 { get; set; }
        public string email_address { get; set; }
    }
}
