//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment_resp_crit
    {
        public int pk1 { get; set; }
        public int deployment_response_pk1 { get; set; }
        public int deployment_criteria_pk1 { get; set; }
    
        public virtual deployment_criteria deployment_criteria { get; set; }
        public virtual deployment_response deployment_response { get; set; }
    }
}
