//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment_criteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deployment_criteria()
        {
            this.deployment_resp_crit = new HashSet<deployment_resp_crit>();
        }
    
        public int pk1 { get; set; }
        public int deployment_pk1 { get; set; }
        public string ref_type { get; set; }
        public string ref_uid { get; set; }
        public Nullable<int> crsmain_pk1 { get; set; }
        public Nullable<int> term_pk1 { get; set; }
        public string course_role { get; set; }
        public Nullable<int> institution_roles_pk1 { get; set; }
        public Nullable<int> mi_node_pk1 { get; set; }
        public Nullable<int> users_pk1 { get; set; }
    
        public virtual deployment deployment { get; set; }
        public virtual mi_node mi_node { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_resp_crit> deployment_resp_crit { get; set; }
    }
}
