//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment_reminder
    {
        public int pk1 { get; set; }
        public int deployment_pk1 { get; set; }
        public Nullable<int> send_time_relative { get; set; }
        public Nullable<System.DateTime> send_time_absolute { get; set; }
        public string send_time_units { get; set; }
        public string send_time_base { get; set; }
        public string repeat_enabled { get; set; }
        public Nullable<int> repeat_interval { get; set; }
        public string repeat_interval_units { get; set; }
        public string message { get; set; }
        public string subject { get; set; }
        public string instrument_link_msg { get; set; }
        public Nullable<System.DateTime> last_sent { get; set; }
    
        public virtual deployment deployment { get; set; }
    }
}
