//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deployment()
        {
            this.clp_sv_survey_deployment = new HashSet<clp_sv_survey_deployment>();
            this.deployment_announcements = new HashSet<deployment_announcements>();
            this.deployment_contact = new HashSet<deployment_contact>();
            this.deployment_criteria = new HashSet<deployment_criteria>();
            this.deployment_list_def = new HashSet<deployment_list_def>();
            this.deployment_mat_list = new HashSet<deployment_mat_list>();
            this.deployment_reminder = new HashSet<deployment_reminder>();
            this.deployment_response = new HashSet<deployment_response>();
        }
    
        public int pk1 { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string collection_key { get; set; }
        public string instrument_type { get; set; }
        public Nullable<int> work_ctx_pk1 { get; set; }
        public Nullable<int> parent_deployment_pk1 { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> scheduled_start_date { get; set; }
        public Nullable<System.DateTime> scheduled_end_date { get; set; }
        public string is_email_deploy { get; set; }
        public string create_ctxt_list { get; set; }
        public string is_course_announce { get; set; }
        public string is_sys_announce { get; set; }
        public string is_perm_course_announce { get; set; }
        public string is_perm_system_announce { get; set; }
        public string is_anonymous { get; set; }
        public string system_announce_subj { get; set; }
        public string system_announce_msg { get; set; }
        public string system_announce_tft { get; set; }
        public string system_announce_link_msg { get; set; }
        public string course_announce_subj { get; set; }
        public string course_announce_msg { get; set; }
        public string course_announce_tft { get; set; }
        public string course_announce_link_msg { get; set; }
        public string email_announce_msg { get; set; }
        public string email_announce_subj { get; set; }
        public string email_announce_from { get; set; }
        public string email_announce_link_msg { get; set; }
        public string submitted_msg { get; set; }
        public string submitted_tft { get; set; }
        public string already_submitted_msg { get; set; }
        public string already_submitted_tft { get; set; }
        public string not_available_msg { get; set; }
        public string not_available_tft { get; set; }
        public Nullable<System.DateTime> dtmodified { get; set; }
        public string course_deployment_ind { get; set; }
        public string org_deployment_ind { get; set; }
        public string user_deployment_ind { get; set; }
        public string unavail_course_org_ind { get; set; }
        public string report_distrib_ind { get; set; }
        public Nullable<System.DateTime> report_distrib_start_date { get; set; }
        public Nullable<System.DateTime> report_distrib_end_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clp_sv_survey_deployment> clp_sv_survey_deployment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_announcements> deployment_announcements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_contact> deployment_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_criteria> deployment_criteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_list_def> deployment_list_def { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_mat_list> deployment_mat_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_reminder> deployment_reminder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_response> deployment_response { get; set; }
    }
}
