//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain_course_coll_uid
    {
        public int pk1 { get; set; }
        public int domain_pk1 { get; set; }
        public int course_main_pk1 { get; set; }
        public int parent_domain_pk1 { get; set; }
        public string batch_uid { get; set; }
    
        public virtual domain_course_coll domain_course_coll { get; set; }
    }
}
