//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public domain()
        {
            this.domain_admin = new HashSet<domain_admin>();
            this.domain_course_categories = new HashSet<domain_course_categories>();
            this.domain_course_coll = new HashSet<domain_course_coll>();
            this.domain_course = new HashSet<domain_course>();
            this.domain_data_source = new HashSet<domain_data_source>();
            this.domain_institution_role = new HashSet<domain_institution_role>();
            this.domain_module_coll = new HashSet<domain_module_coll>();
            this.domain_module = new HashSet<domain_module>();
            this.domain_org_categories = new HashSet<domain_org_categories>();
            this.domain_organization_coll = new HashSet<domain_organization_coll>();
            this.domain_organization = new HashSet<domain_organization>();
            this.domain_system_role = new HashSet<domain_system_role>();
            this.domain_user_coll = new HashSet<domain_user_coll>();
            this.domain_user = new HashSet<domain_user>();
            this.mi_node = new HashSet<mi_node>();
        }
    
        public int pk1 { get; set; }
        public System.DateTime dtcreated { get; set; }
        public Nullable<System.DateTime> dtmodified { get; set; }
        public string batch_uid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string default_ind { get; set; }
        public string manual_ind { get; set; }
        public string crs_include_crit { get; set; }
        public string crs_check_availability_ind { get; set; }
        public string crs_check_availability_val { get; set; }
        public string crs_check_row_status_ind { get; set; }
        public int crs_check_row_status_val { get; set; }
        public string crs_check_enrollment_ind { get; set; }
        public string crs_check_enrollment_val { get; set; }
        public string crs_check_categories_ind { get; set; }
        public string crs_check_data_source_ind { get; set; }
        public string crs_check_list_ind { get; set; }
        public string org_include_crit { get; set; }
        public string org_check_availability_ind { get; set; }
        public string org_check_availability_val { get; set; }
        public string org_check_row_status_ind { get; set; }
        public int org_check_row_status_val { get; set; }
        public string org_check_enrollment_ind { get; set; }
        public string org_check_enrollment_val { get; set; }
        public string org_check_categories_ind { get; set; }
        public string org_check_data_source_ind { get; set; }
        public string org_check_list_ind { get; set; }
        public string usr_include_crit { get; set; }
        public string usr_check_availability_ind { get; set; }
        public string usr_check_availability_val { get; set; }
        public string usr_check_row_status_ind { get; set; }
        public int usr_check_row_status_val { get; set; }
        public string usr_check_enrollment_ind { get; set; }
        public int usr_check_enrollment_val { get; set; }
        public string usr_check_department_ind { get; set; }
        public string usr_check_privacy_ind { get; set; }
        public string usr_check_privacy_val { get; set; }
        public string usr_check_inst_role_ind { get; set; }
        public string usr_check_sys_role_ind { get; set; }
        public string usr_check_data_source_ind { get; set; }
        public string usr_check_list_ind { get; set; }
        public string tab_include_crit { get; set; }
        public string tab_check_availability_ind { get; set; }
        public string tab_check_availability_val { get; set; }
        public string tab_check_list_ind { get; set; }
        public string mod_include_crit { get; set; }
        public string mod_check_availability_ind { get; set; }
        public string mod_check_availability_val { get; set; }
        public string mod_check_list_ind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_admin> domain_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_course_categories> domain_course_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_course_coll> domain_course_coll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_course> domain_course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_data_source> domain_data_source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_institution_role> domain_institution_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_module_coll> domain_module_coll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_module> domain_module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_org_categories> domain_org_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_organization_coll> domain_organization_coll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_organization> domain_organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_system_role> domain_system_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_user_coll> domain_user_coll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_user> domain_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mi_node> mi_node { get; set; }
    }
}
