//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mi_node()
        {
            this.deployment_criteria = new HashSet<deployment_criteria>();
            this.mi_node1 = new HashSet<mi_node>();
        }
    
        public int pk1 { get; set; }
        public Nullable<int> parent_pk1 { get; set; }
        public int domain_pk1 { get; set; }
        public string batch_uid { get; set; }
        public int data_src_pk1 { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime dtcreated { get; set; }
        public Nullable<System.DateTime> dtmodified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deployment_criteria> deployment_criteria { get; set; }
        public virtual domain domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mi_node> mi_node1 { get; set; }
        public virtual mi_node mi_node2 { get; set; }
    }
}
