//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EacSurveys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBLEARNEntities : DbContext
    {
        public BBLEARNEntities()
            : base("name=BBLEARNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clp_sv_ac_template> clp_sv_ac_template { get; set; }
        public virtual DbSet<clp_sv_answer_choice> clp_sv_answer_choice { get; set; }
        public virtual DbSet<clp_sv_question> clp_sv_question { get; set; }
        public virtual DbSet<clp_sv_question_response> clp_sv_question_response { get; set; }
        public virtual DbSet<clp_sv_question_sog> clp_sv_question_sog { get; set; }
        public virtual DbSet<clp_sv_question_tag> clp_sv_question_tag { get; set; }
        public virtual DbSet<clp_sv_sq_template> clp_sv_sq_template { get; set; }
        public virtual DbSet<clp_sv_subquestion> clp_sv_subquestion { get; set; }
        public virtual DbSet<clp_sv_survey> clp_sv_survey { get; set; }
        public virtual DbSet<clp_sv_survey_deployment> clp_sv_survey_deployment { get; set; }
        public virtual DbSet<clp_sv_survey_user> clp_sv_survey_user { get; set; }
        public virtual DbSet<clp_sv_visual_element> clp_sv_visual_element { get; set; }
        public virtual DbSet<deployment> deployments { get; set; }
        public virtual DbSet<deployment_announcements> deployment_announcements { get; set; }
        public virtual DbSet<deployment_contact> deployment_contact { get; set; }
        public virtual DbSet<deployment_criteria> deployment_criteria { get; set; }
        public virtual DbSet<deployment_list_def> deployment_list_def { get; set; }
        public virtual DbSet<deployment_mat_list> deployment_mat_list { get; set; }
        public virtual DbSet<deployment_recipient> deployment_recipient { get; set; }
        public virtual DbSet<deployment_reminder> deployment_reminder { get; set; }
        public virtual DbSet<deployment_resp_crit> deployment_resp_crit { get; set; }
        public virtual DbSet<deployment_response> deployment_response { get; set; }
        public virtual DbSet<domain> domains { get; set; }
        public virtual DbSet<domain_admin> domain_admin { get; set; }
        public virtual DbSet<domain_course> domain_course { get; set; }
        public virtual DbSet<domain_course_categories> domain_course_categories { get; set; }
        public virtual DbSet<domain_course_coll> domain_course_coll { get; set; }
        public virtual DbSet<domain_course_coll_uid> domain_course_coll_uid { get; set; }
        public virtual DbSet<domain_data_source> domain_data_source { get; set; }
        public virtual DbSet<domain_institution_role> domain_institution_role { get; set; }
        public virtual DbSet<domain_module> domain_module { get; set; }
        public virtual DbSet<domain_module_coll> domain_module_coll { get; set; }
        public virtual DbSet<domain_org_categories> domain_org_categories { get; set; }
        public virtual DbSet<domain_org_coll_uid> domain_org_coll_uid { get; set; }
        public virtual DbSet<domain_organization> domain_organization { get; set; }
        public virtual DbSet<domain_organization_coll> domain_organization_coll { get; set; }
        public virtual DbSet<domain_system_role> domain_system_role { get; set; }
        public virtual DbSet<domain_user> domain_user { get; set; }
        public virtual DbSet<domain_user_coll> domain_user_coll { get; set; }
        public virtual DbSet<domain_user_coll_uid> domain_user_coll_uid { get; set; }
        public virtual DbSet<mi_node> mi_node { get; set; }
    }
}
